# Generated by Django 4.2.5 on 2023-09-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_fullname_myuser_join_date_myuser_nickname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='date_of_birth',
            new_name='birthday',
        ),
    ]
